version: "3.9"
services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-encryption-poc
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DB_NAME
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:1.3.2
    container_name: opensearch-encryption-poc
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    restart: always
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9200", "-ku", "admin:admin"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  dbdata:
  opensearch-data: